import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';
import '../../utils/file_saver/file_saver.dart';

class TerminalOutput extends StatefulWidget {
  final String output;
  final bool isRunning;
  final VoidCallback? onClear;
  final double height;
  final String filterCommand;

  const TerminalOutput({
    super.key,
    required this.output,
    this.isRunning = false,
    this.onClear,
    this.height = 300,
    this.filterCommand = '',
  });

  @override
  State<TerminalOutput> createState() => _TerminalOutputState();
}

class _TerminalOutputState extends State<TerminalOutput> {
  final ScrollController _scrollController = ScrollController();
  bool _autoScroll = true;

  @override
  void didUpdateWidget(TerminalOutput oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (_autoScroll && widget.output != oldWidget.output) {
      WidgetsBinding.instance.addPostFrameCallback((_) {
        _scrollToBottom();
      });
    }
  }

  void _scrollToBottom() {
    if (_scrollController.hasClients) {
      _scrollController.animateTo(
        _scrollController.position.maxScrollExtent,
        duration: const Duration(milliseconds: 200),
        curve: Curves.easeOut,
      );
    }
  }

  String _getFilteredOutput() {
    if (widget.filterCommand.isEmpty) return widget.output;

    List<String> lines = widget.output.split('\n');
    
    // Simple parser for the grep command generated by UniversalFilterWidget
    // Format: grep -E "pattern" | grep -Ev "pattern" ...
    // Note: This is a basic implementation and might not cover all edge cases of shell commands
    
    final parts = widget.filterCommand.split('|');
    
    for (var part in parts) {
      part = part.trim();
      bool isOr = false;
      if (part.startsWith('|')) { // Handle || (OR) which might come as empty split if we split by |
         // The split logic above is too simple for ||. 
         // UniversalFilterWidget uses ' | ' for AND and ' || ' for OR.
      }
    }

    // Better approach: Split by ' ' to find grep commands? 
    // UniversalFilterWidget generates: grep -E "pattern" [|/||] grep ...
    
    // Let's implement a robust enough parser for the specific output of UniversalFilterWidget
    
    // We will process the command string to extract filters
    // This is a simplified client-side simulation of grep
    
    List<String> resultLines = [];
    
    // If the command is complex, we might just fail gracefully or try basic filtering
    // For now, let's assume standard AND chaining as that's the most common
    
    // Split by pipe for AND chain
    final commands = widget.filterCommand.split(' | ');
    
    List<String> currentLines = List.from(lines);
    
    for (var cmd in commands) {
      cmd = cmd.trim();
      // Handle OR (||) within a segment? UniversalFilterWidget puts || between greps
      // But wait, split(' | ') won't catch ' || '.
      
      if (cmd.contains(' || ')) {
        // OR logic
        final orParts = cmd.split(' || ');
        Set<String> orMatchedLines = {};
        
        for (var orCmd in orParts) {
          orMatchedLines.addAll(_applyGrep(currentLines, orCmd));
        }
        currentLines = orMatchedLines.toList();
        // Restore order?
        currentLines.sort((a, b) => lines.indexOf(a).compareTo(lines.indexOf(b)));
      } else {
        // AND logic
        currentLines = _applyGrep(currentLines, cmd);
      }
    }
    
    return currentLines.join('\n');
  }

  List<String> _applyGrep(List<String> sourceLines, String grepCmd) {
    grepCmd = grepCmd.trim();
    if (!grepCmd.startsWith('grep')) return sourceLines;

    bool invert = grepCmd.contains('-v');
    
    // Extract pattern: grep -E "pattern" or grep -Ev "pattern"
    // Find the content inside quotes
    int startIndex = grepCmd.indexOf('"');
    int endIndex = grepCmd.lastIndexOf('"');
    
    if (startIndex == -1 || endIndex == -1 || startIndex >= endIndex) return sourceLines;
    
    String pattern = grepCmd.substring(startIndex + 1, endIndex);
    
    try {
      final regex = RegExp(pattern, caseSensitive: false); // grep usually case sensitive but let's be loose or check flags
      // UniversalFilterWidget doesn't seem to set -i, so default is case sensitive. 
      // But for better UX let's assume case insensitive or check if UniversalFilterWidget adds -i?
      // Looking at UniversalFilterWidget code, it doesn't add -i. It uses regex directly.
      // Let's stick to the generated regex.
      
      final strictRegex = RegExp(pattern);

      return sourceLines.where((line) {
        bool matches = strictRegex.hasMatch(line);
        return invert ? !matches : matches;
      }).toList();
    } catch (e) {
      return sourceLines; // Invalid regex
    }
  }

  @override
  Widget build(BuildContext context) {
    final filteredOutput = _getFilteredOutput();
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    return Container(
      height: widget.height,
      decoration: BoxDecoration(
        color: const Color(0xFF0F172A), // Premium Dark Blue
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.white.withOpacity(0.08)),
        boxShadow: [
          BoxShadow(
            color: const Color(0xFF000000).withOpacity(0.25),
            offset: const Offset(0, 4),
            blurRadius: 10,
          ),
        ],
      ),
      child: Column(
        children: [
          // Toolbar
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
            decoration: BoxDecoration(
              color: Colors.white.withOpacity(0.03),
              borderRadius: const BorderRadius.vertical(top: Radius.circular(12)),
              border: Border(bottom: BorderSide(color: Colors.white.withOpacity(0.05))),
            ),
            child: Row(
              children: [
                Icon(Icons.terminal_rounded, size: 16, color: colorScheme.primary.withOpacity(0.8)),
                const SizedBox(width: 8),
                Text(
                  'Terminal Output',
                  style: GoogleFonts.outfit(
                    fontSize: 12,
                    fontWeight: FontWeight.w600,
                    color: Colors.white70,
                    letterSpacing: 0.5,
                  ),
                ),
                if (widget.isRunning) ...[
                  const SizedBox(width: 12),
                  SizedBox(
                    width: 12,
                    height: 12,
                    child: CircularProgressIndicator(
                      strokeWidth: 2,
                      valueColor: AlwaysStoppedAnimation<Color>(colorScheme.secondary),
                    ),
                  ),
                ],
                const Spacer(),
                if (widget.filterCommand.isNotEmpty)
                   Padding(
                     padding: const EdgeInsets.only(right: 8.0),
                     child: Container(
                       padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                       decoration: BoxDecoration(
                         color: colorScheme.primary.withOpacity(0.15),
                         borderRadius: BorderRadius.circular(6),
                         border: Border.all(color: colorScheme.primary.withOpacity(0.3)),
                       ),
                       child: Row(
                         children: [
                           Icon(Icons.filter_alt_outlined, size: 10, color: colorScheme.primary),
                           const SizedBox(width: 4),
                           Text(
                             'Filtered',
                             style: GoogleFonts.inter(
                               fontSize: 10, 
                               color: colorScheme.primary,
                               fontWeight: FontWeight.w600,
                             ),
                           ),
                         ],
                       ),
                     ),
                   ),
                _buildToolbarButton(
                  icon: Icons.copy_rounded,
                  tooltip: 'Copy Output',
                  onPressed: () {
                    Clipboard.setData(ClipboardData(text: filteredOutput));
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(
                        content: const Text('Output copied to clipboard'),
                        backgroundColor: colorScheme.surfaceContainerHighest,
                        behavior: SnackBarBehavior.floating,
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                      ),
                    );
                  },
                ),
                const SizedBox(width: 4),
                _buildToolbarButton(
                  icon: Icons.vertical_align_bottom_rounded,
                  tooltip: 'Auto-scroll',
                  isActive: _autoScroll,
                  onPressed: () {
                    setState(() {
                      _autoScroll = !_autoScroll;
                      if (_autoScroll) _scrollToBottom();
                    });
                  },
                  activeColor: colorScheme.primary,
                ),
                const SizedBox(width: 4),
                 _buildToolbarButton(
                    icon: Icons.download_rounded,
                    tooltip: 'Download Log',
                    onPressed: () {
                       FileSaver.saveFile(filteredOutput, 'terminal.log');
                    },
                  ),
                  if (widget.onClear != null) ...[
                    const SizedBox(width: 4),
                    _buildToolbarButton(
                      icon: Icons.delete_outline_rounded,
                      tooltip: 'Clear',
                      onPressed: widget.onClear,
                      hoverColor: Colors.red.withOpacity(0.2),
                      iconColor: Colors.white54,
                    ),
                  ],
              ],
            ),
          ),
          // Output Area
          Expanded(
            child: SelectionArea(
              child: ListView(
                controller: _scrollController,
                padding: const EdgeInsets.all(16),
                children: [
                  Text(
                    filteredOutput.isEmpty 
                      ? (widget.output.isEmpty ? 'Waiting for command...' : 'No matches found') 
                      : filteredOutput,
                    style: GoogleFonts.jetBrainsMono(
                      fontSize: 13,
                      height: 1.6,
                      color: filteredOutput.isEmpty ? Colors.white24 : const Color(0xFFE2E8F0),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildToolbarButton({
    required IconData icon,
    required String tooltip,
    required VoidCallback? onPressed,
    bool isActive = false,
    Color? activeColor,
    Color? hoverColor,
    Color iconColor = Colors.white60,
  }) {
    return  Tooltip(
      message: tooltip,
      child: Material(
        color: Colors.transparent,
        child: InkWell(
          onTap: onPressed,
          borderRadius: BorderRadius.circular(6),
          hoverColor: hoverColor ?? Colors.white.withOpacity(0.1),
          child: Container(
            padding: const EdgeInsets.all(6),
            decoration: isActive ? BoxDecoration(
              color: (activeColor ?? Colors.blue).withOpacity(0.2),
              borderRadius: BorderRadius.circular(6),
            ) : null,
            child: Icon(
              icon, 
              size: 16, 
              color: isActive ? (activeColor ?? Colors.blue) : iconColor,
            ),
          ),
        ),
      ),
    );
  }
}
